version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    open-pull-request-limit: 0
    groups:
      all:
        applies-to: security-updates
        patterns:
          - "*"
